In [1]:
# Complete NumPy tutorial


In [2]:
import numpy as np
import sys

In [3]:
# We can store all types of arrays
# How are Lists different from NumPy?
# List = slow, NumPy = fast
# for example 
# 5 -> 00000101 in binary ->NumPy-> 00000000 00000000 00000000 00000101 (Int32), fixed type
# 5 ->Lists-> size is very big, because lists consist of [size, reference count, Object type, Object value]
# and this is a lot of bytes, also type checking
# data is spred, scattered around in a list, in numpy the data blocks are tightened to a continuos 

In [4]:
# Used for Mathematics, Plotting, Backend, Machine learning

In [19]:
# Inititalise a 1-D array, specify the type of data
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# number of dimensions
a.ndim

1

In [11]:
# Shape (rows, columns)
b.shape

(2, 3)

In [14]:
# Type of the data inside
a.dtype

dtype('int16')

In [18]:
# Get Size in bytes for a single item inside
a.itemsize

8

In [22]:
# Get total size - total number of atomized elements
b.size

6

In [23]:
# Accessing/Changing specific elements, rows, columns, etc
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
# Get a specific element [row, column]
a[1, 5]
a[1, -2]

13

In [26]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a specific column
a[:, 4]

array([ 5, 12])

In [29]:
# Get [row, startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [30]:
# Change a value in an array
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [32]:
# Change a column in an array
a[:, 3] = [55, 66]
print(a)

[[ 1  2  3 55  5  6  7]
 [ 8  9 10 66 12 20 14]]


In [37]:
#3-D example
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
#lets get 7 from there 
b[1, 1, 0]

7

In [39]:
# Initializing Different Types of Arrays

In [42]:
# All 0s matrix
a0 = np.zeros((2, 2, 2))
print(a0)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [44]:
# All 1s matrix, pass a tuple
a1 = np.ones((2, 2, 2))
print(a1)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [45]:
# All any-number matrix
np.full((2, 2), 99) 


array([[99, 99],
       [99, 99]])

In [46]:
# Any other number, use the shape of an another array
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [47]:
# Random decimal numbers
np.random.rand(2, 2)

array([[0.25069222, 0.91292701],
       [0.49622244, 0.26221175]])

In [48]:
np.random.randint(4, 7, size=(3, 3))

array([[5, 6, 4],
       [5, 6, 6],
       [4, 5, 5]])

In [49]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 4, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [70]:
res = np.ones([5, 5])
res[2, 2] = 9
res[1, 1:4] = 0
res[3, 1:4] = 0
res[1:4, 1] = 0
res[1:4, 3] = 0
print(res)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [71]:
# another option:
r = np.ones([5, 5])
z = np.zeros([3, 3])
z[1, 1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [72]:
r[1:4, 1:4] = z
print(r)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
# careful copying arrays!
a = np.array([1, 2, 3])
b = a
b[0] = 100
# -> will update a!
# to do what we need -> use copy function

In [76]:
a1 = np.array([1, 2, 3])
b = a1.copy()
b[0] = 100

print(b)

[100   2   3]


In [77]:
# Math n numpy

In [78]:
n = np.array([1, 2, 3, 4])
print(n + 2)

[3 4 5 6]


In [79]:
print( n - 2)

[-1  0  1  2]


In [80]:
for i in n:
    print(i + 2)

3
4
5
6


In [81]:
m = np.array([2, 4, 6, 7])
print(n + m)

[ 3  6  9 11]


In [82]:
np.cos(m)

array([-0.41614684, -0.65364362,  0.96017029,  0.75390225])

In [83]:
np.sin(m)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.6569866 ])

In [85]:
# Linear algebra
# docs.scipy.org/doc/numpy/reference/routines.linalg.html
a = np.full((2, 3), 1) #2 by 3 matrix with 1s
b = np.full((3, 2), 2)
# to multiply them ->
np.matmul(a, b)

array([[6, 6],
       [6, 6]])

In [87]:
# determinant np.linalg.det
np.linalg.det(np.matmul(a, b))

0.0

In [90]:
#Statistics
stats = np.array([[1, 2, 3], [4, 5, 6]])
np.min(stats)
np.max(stats, axis=1)

array([3, 6])

In [99]:
# Solve the system of equations 3 * x0 + x1 = 9 and x0 + 2 * x1 = 8:
vec1 = np.array([[3,1], [1,2]])
vec2 = np.array([9,8])
x = np.linalg.solve(vec1, vec2)
x
# x1 = 2, x2 = 3

array([2., 3.])

In [94]:
np.sum(stats, axis=1)

array([ 6, 15])